name: Build Kivy APK

on:
  workflow_dispatch:   # запуск вручную с вкладки Actions

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ env.PATH }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install buildozer & dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel wget
        pip install --upgrade Cython virtualenv
        pip install buildozer

    - name: Install Android SDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d latest
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

    - name: Build APK
      run: |
        buildozer init || true
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: qrpass-apk
        path: bin/*.apk
